archives:
  - format: binary
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
changelog:
  use: github
  sort: asc
universal_binaries:
  - replace: false
